### ISSUE TITLE
/users/:id is showing /profiles/:id - is this what we want?

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#116]
We need to show actual user on /users/:id and then think how we are going to display profiles

**Comment by knirirr** [comment]
This was exactly as I designed things to work, the profile being separate from the user because the user object contains only one thing we might want to show to the public - the username. Everything else other than perhaps the email address is something that needs to be hidden and should not be accessible to the user for editing. They might need to change their password but that can be done by means of the usual Devise mechanism.
