### ISSUE TITLE
Add regenerate authentication token functionality on user's profile page

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#124]

**Comment by njall** [comment]
![screen shot 2016-02-18 at 17 03 32](https://cloud.githubusercontent.com/assets/860475/13151344/a8f51e60-d661-11e5-96b1-859f5e0e6412.png)

Same thing as the CKAN version - if the user decided they need a new authentication token because it's at risk or otherwise - there should be a regenerate button as in the image that replaces the token associated with their account for a newly generated one.
