### ISSUE TITLE
Make sure all dependent objects (packages, workflows, etc) are deleted when owner - user/provider is destroyed 

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#148]

**Comment by anenadic** [comment]
Or at least set to nil, to avoid orphaned objects error in the case we do not want to delete, say, materials.

**Comment by njall** [comment]
I've set it so that some re-assign to default_user and some destroy whenever their owner is deleted.
profile = destroy
packages = destroy
workflows = destroy

materials = reassign
content_providers = reassign
events = reassign
nodes = reassign

The deletion of a Content Provider, at present, destroys the materials and events associated with it.

Shall we mark this as closed @anenadic ? or do you want to rethink this further?
