### ISSUE TITLE
Create/update actions should strip HTML from all fields (but keep Markdown markup)

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#168]

**Comment by knirirr** [comment]
Presumably the NGS Registry scraper is one that is being referred to by this ticket. Looking at the output of that (https://bioinformatics.upsc.se/trainers/details.json) I see that it's full of Markdown which is being copied directly into the TeSS material, including the menus &c. Should not the procedure here be to parse the Markdown and extract the info. into the relevant fields, rather than retaining it?

**Comment by anenadic** [comment]
Agreed - the page does not look nice with all the menus pulled out, etc. 

Looks like we are already extracting keywords out of Markdown. We might just extract description.

**Comment by knirirr** [comment]
ActionView::Base.full_sanitizer.sanitize() seems to do the trick for HTML. I've added it to the materials (short_description, long_description) and events (description) controllers.
