### ISSUE TITLE
Add support for EDAM-based controlled vocabularies

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#20]
For scientific topic and target audience fields of materials.

**Comment by njall** [comment]
Initially I used BioPortal Widget for EDAM autocomplete to implement this ( http://www.bioontology.org/wiki/index.php/NCBO_Widgets#How_to_use_NCBO_Widgets)
The commit for this implementation can be found [here](
https://github.com/ElixirUK/TeSS/commit/fe4f35bb758154fa3e53fa088667a26e99d175cd)

However, I've since been informed by a colleague that their attempts at using BioPortal autocomplete via ajax was too slow - so they created a local copy that delivers all options to the client on pageLoad so the autocomplete runs locally on their machine. 

As such I've converted EDAM topics to .yml format and will implement a dictionary similar to how LicenceDictionary was implemented.

**Comment by anenadic** [comment]
Needs associating with training materials, many-to-many.

**Comment by njall** [comment]
Done. Can pass an array of ids using key 'scientific_topic_ids' to assign topics to a material
