### ISSUE TITLE
Have icon to show stale materials

### ISSUE THREAD

**Issue by njall** [ElixirUK/TeSS#311]
Currently when we run scrapers we update the existing ones and create new ones, but nothing happens to the ones that are no longer available. 
We could implement an icon (such as a [warning symbol](http://fontawesome.io/icon/exclamation-circle/)) on the material page to show that this material might no longer be available. This would be shown if the updated_date is more than two weeks before the current date. 
Also add hover over text to explain what this means ([like how hover over is implemented for events icons](https://tess.elixir-uk.org/events/the-genomics-era-the-future-of-genetics-in-medicine)).

"Curators" can then go through and remove the ones that are no longer there. The only problem is ones added manually will be flagged to so. We don't have many for now so not a big problem but we may need to add a field to the model that says whether it was added by scraper or added by form

**Comment by knirirr** [comment]
It seems that updated_at is only changed if something actually changes in the model; at least within the console simply calling save doesn't seem to update that field. Would you mind taking a look if you have a moment to confirm this? If I'm not mistaken then this might cause a problem if scrapers aren't actually updating anything.
Would it perhaps be worth adding a "last scraped at" timestamp which could be sent by the scraper itself? This field could then be used instead of the last updated field. Unfortunately this would involve a lot more change than simply using the updated_at field.

**Comment by njall** [comment]
Yep, I think that would be a good idea. We can also then differentiate a
scraped resource from a manually inputted one.

The reason I suggested the above was because when the scraper calls the
update method it always updates the record even when the content is exactly
the same; so the updated date gets updated everytime it's ran. If you look
at any material or event in TeSS uploaded by scraper the updated date will
be today even though the content hasn't changed. I suspect it's something
to do with the conversion of nil to [] in the model for array fields such
as authors and keywords. It would explain why not finding the scraper == to
the database record


Niall Beard

**Comment by knirirr** [comment]
Ah, yes - my save in the shell wouldn't have been doing any of the conversions and so would not have changed anything.
I'll see about getting the scrapers to send a scraped_at timestamp; if this is nil by default then that should serve to mark the manually added ones.

**Comment by knirirr** [comment]
This is in the last_scraped branch.

**Comment by knirirr** [comment]
Now deployed.
