### ISSUE TITLE
Filters tend to dissapear randomly - filtering logic needs re-thinking

### ISSUE THREAD

**Issue by anenadic** [ElixirUK/TeSS#40]

**Comment by anenadic** [comment]
Perhaps we do 'or' for filters in the same category and 'and' for filters in different categories.

**Comment by njall** [comment]
Fixed the disappearing filters issue. 

The error:
Strange bug: modifications to a variable that was a duplication of 'request.params' (duplicated using .dup) still affected the original request.params. Using the .delete on the variable deleted from the original so each time the remove_filter method was called, the value would be deleted from the parameter variable. No idea why that is but using 'params' rather than 'request.params' does not have that behaviour and works
